server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:mysql://localhost/spring_in_action
    username: liuxu
    password: liuxu
    initialization-mode: always
  jpa:
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

greeting:
  message: Refresh Config Test
