CREATE TABLE singer (
    ID int NOT NULL AUTO_INCREMENT,
    FIRST_NAME varchar(60) NOT NULL,
    LAST_NAME varchar(40) NOT NULL,
    BIRTH_DATE date DEFAULT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UQ_SINGER_1 (FIRST_NAME, LAST_NAME)
);